defmodule NimbleTemplate.Addons.Phoenix.Api.ConfigTest do
  use NimbleTemplate.AddonCase, async: false

  describe "#apply!/2" do
    test "removes cache_static_manifest setting in config/prod.exs", %{
      project: project,
      test_project_path: test_project_path
    } do
      in_test_project!(test_project_path, fn ->
        ApiAddons.Config.apply!(project)

        assert_file("config/prod.exs", fn file ->
          refute file =~ "cache_static_manifest: \"priv/static/cache_manifest.json\""

          refute file =~ """
                 # For production, don't forget to configure the url host
                 # to something meaningful, Phoenix uses this information
                 # when generating URLs.

                 # Note we also include the path to a cache manifest
                 # containing the digested version of static files. This
                 # manifest is generated by the `mix phx.digest` task,
                 # which you should run after static files are built and
                 # before starting your production server.
                 """
        end)
      end)
    end
  end
end
