name: Reusable Mix project

on:
  workflow_call:
    inputs:
      new_project_options:
        required: true
        type: string

env:
  OTP_VERSION: 24.2.2
  ELIXIR_VERSION: 1.13.3
  BASE_PROJECT_DIRECTORY: sample_project
  MIX_ENV: test
  
jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Elixir ${{ env.ELIXIR_VERSION }} and OTP ${{ env.OTP_VERSION }}
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      
      - name: Create Mix project
        run: make create_mix_project PROJECT_DIRECTORY=$BASE_PROJECT_DIRECTORY OPTIONS="${{ inputs.new_project_options }}"

      - name: Apply Mix template
        run: make apply_mix_template PROJECT_DIRECTORY=$BASE_PROJECT_DIRECTORY

      # Verify the new project after applying the nimble_template

      - name: Install Elixir Dependencies
        run: cd $BASE_PROJECT_DIRECTORY && mix deps.get

      - name: Compile dependencies
        run: cd $BASE_PROJECT_DIRECTORY && mix compile --warnings-as-errors --all-warnings

      - name: Run mix codebase
        run: cd $BASE_PROJECT_DIRECTORY && mix codebase

      - name: Run mix test
        run: cd $BASE_PROJECT_DIRECTORY && mix test
