name: "Test API variant on custom API project"

on: push

env:
  OTP_VERSION: 23.3
  ELIXIR_VERSION: 1.11.4
  PHOENIX_VERSION: 1.5.7

jobs:   
  unit_test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:12.3
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
          
      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
              
      - uses: nimblehq/elixir-templates@composite_1.4
        with:
          new_project_options: '--no-html --no-webpack --module=CustomModule --app=custom_app'
          variant: 'api'
