name: Upgrade Stack

on:
  workflow_dispatch:
    inputs:
      elixirVersion:
        description: "Elixir version"
        required: false
        type: string

      erlangVersion:
        description: "Erlang version"
        required: false
        type: string

      alpineVersion:
        description: "Alpine version"
        required: false
        type: string

      nodeVersion:
        description: "Node version"
        required: false
        type: string

env:
  PHOENIX_VERSION: 1.6.11
  MIX_ENV: test

jobs:
  upgrade_stack:
    name: Upgrade Stack
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: /home/runner/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-

      - name: Install dependencies in .tool-versions
        uses: asdf-vm/actions/install@v1

      - name: Install rebar
        run: mix local.rebar --force

      - name: Install hex
        run: mix local.hex --force

      - name: Cache Elixir build
        uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile dependencies
        run: mix compile --warnings-as-errors --all-warnings

      - name: Install Phoenix ${{ env.PHOENIX_VERSION }}
        run: make install_phoenix PHOENIX_VERSION=${{ env.PHOENIX_VERSION }}

      - name: Upgrade Stack
        run: mix nimble_template.upgrade_stack --elixir ${{ github.event.inputs.elixirVersion }} --erlang ${{ github.event.inputs.erlangVersion }} --node ${{ github.event.inputs.nodeVersion }} --alpine ${{ github.event.inputs.alpineVersion }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: andyduong1920
          token: ${{ secrets.WIKI_ACTION_TOKEN }}
          commit-message: Upgrade stack versions
          committer: Nimble Bot <bot@nimblehq.co>
          branch: chore/upgrade-stack-versions
          delete-branch: true
          title: '[Chore] Upgrade stack versions'
          labels: |
            type : chore
          body: |
            ## What happened

            Upgrade stack versions

            ## Insight

            Automatically created by the Upgrade stacks workflow.

            ## Proof Of Work

            On the Files changed tab
