name: Verify Release version

on:
  push:
    branches:
      - 'release/**'

env:
  OTP_VERSION: 23.3
  ELIXIR_VERSION: 1.11.4
  PHOENIX_VERSION: 1.6.6
  MIX_ENV: test

jobs:
  release_version_test:
    name: Verify the Release version
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

     - name: Set up Elixir ${{ env.ELIXIR_VERSION }} and OTP ${{ env.OTP_VERSION }}
       uses: erlef/setup-elixir@v1
       with:
         otp-version: ${{ env.OTP_VERSION }}
         elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile dependencies
        run: mix compile --warnings-as-errors --all-warnings

      - name: Install Phoenix ${{ env.PHOENIX_VERSION }}
        run: make install_phoenix PHOENIX_VERSION=${{ env.PHOENIX_VERSION }}

      - name: Run Tests
        run: mix test --only release_version
